spring.application.name=api-gateway
server.port=9000

# Backend service URLs
services.customer.url=http://localhost:8081
services.movie.url=http://localhost:8082
services.booking.url=http://localhost:8083

# Actuator: expose health endpoint
management.endpoints.web.exposure.include=health