spring.application.name=api-gateway
server.port=9000

# URL cac service dich
services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082

# TODO 4.9: Issuer URI cua Keycloak realm.
# Spring tu goi {issuer-uri}/.well-known/openid-configuration -> jwks_uri -> tai public key
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm

# Actuator: chi mo health
management.endpoints.web.exposure.include=health

# (Tuy chon) debug bao mat khi gap 401
# logging.level.org.springframework.security=DEBUG